apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name}}
  labels:
    {{- include "visits-service-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "visits-service-chart.selectorLabels" . | nindent 4 }}
