apiVersion: v1
kind: Service
metadata:
  name: service-{{.Chart.Name}}
  labels:
    {{- include "api-gateway-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway-chart.selectorLabels" . | nindent 4 }}
