apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "api-gateway-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-gateway-chart.selectorLabels" . | nindent 4 }}
