phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "Building Terraform infrastructure"
      - cd terraform-directory
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Deploying Kubernetes manifests"
      - kubectl apply -f kubernetes-manifests-directory