version: 0.2

phases:
  pre_build:
    commands:
      - echo Test started on `date`
      - echo "ru maven tests on microservices code"
      - ./mvnw clean test

  build:
    commands:
      - echo Build started on `date`
      - echo "run maven build the microservices code"
      - ./mvnw clean install

  post_build:
    commands:
      - echo Build Maven Complete on `date`


artifacts:
  files:
    - '**/*'