---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: spring-petclinic
type: Opaque
data:
  mysql-root-password: c3ByaW5nYm9vdAo=
  mysql-replication-password: c3ByaW5nYm9vdAo=
  mysql-password: c3ByaW5nYm9vdAo=
