---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: spring-petclinic
type: Opaque
data:
  mysql-root-password: c3ByaW5nYm9vdAo=
  mysql-replication-password: c3ByaW5nYm9vdAo=
  mysql-password: c3ByaW5nYm9vdAo=

---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: spring-petclinic
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://petclinic-mysql/petclinic-db
  SPRING_DATASOURCE_USERNAME: petclinic