apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-petclinic
spec:
  selector:
    app : api-gateway
  type: LoadBalancer
  ports: 
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 8080
status:
  loadBalancer: {}
  