# Chart Values

auth: 
  database: service_instance_db
  password: ""
  username: ""
  rootPassword: ""
  createDatabase: true
  existingSecret: mysql-secret
  replicationUser: replicator
  usePasswordFiles: false
  customPasswordFiles: {}
  replicationPassword: ""