# Chart Values

auth: 
  database: service_instance_db
  password: ""
  username: petclinic
  rootPassword: ""
  createDatabase: true
  existingSecret: mysql-secret
  replicationUser: replicatorpetclinic-db
  usePasswordFiles: false
  customPasswordFiles: {}
  replicationPassword: ""


replication:
  ## Enable replication. This enables the creation of replicas of MySQL. If false, only a
  ## master deployment would be created
  ##
  enabled: false