apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: spring-petclinic
spec:
  type: ClusterIP
  selector:
    app: visits-service
  ports:
  - port: 8080
    targetPort: 8080
