apiVersion: v1
kind: Service
metadata:
  name: service-{{.Chart.Name}}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "customers-service-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "customers-service-chart.selectorLabels" . | nindent 4 }}
