apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
  namespace: spring-petclinic
spec:
  type: ClusterIP
  selector:
    app: vets-service
  ports:
  - port: 8080
    targetPort: 8080
